config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get "withdraw"
    end
  end
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :categories
  resources :courses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :courses, dependent: :destroy
  has_ancestry
  default_scope -> { order(created_at: :asc) }
  validates :user_id, presence: true
  validates :name, presence: true
  validates :credits, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  has_many :categories, dependent: :destroy
  has_many :courses, dependent: :destroy
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.where(user_id: current_user.id)
    @all_credits = 0
    @categories.each do |category|
      @all_credits += category.credits if category.root?   #親区分だけ足す
    end
    @all_credits #単位の総数
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      flash[:success] = "追加しました"
      redirect_to categories_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "更新しました"
      redirect_to categories_path
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    Category.find(params[:id]).destroy
    flash[:notice] = "削除しました"
    redirect_to categories_path, status: :see_other
  end

  private
    def category_params
      params[:category][:ancestry] = nil if params[:category][:ancestry].blank?
      params.require(:category).permit(:name, :credits, :ancestry).merge(user_id: current_user.id)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    # @courses = Course.where(user_id: current_user.id)
    @categories = Category.where(user_id: current_user.id)
    @all_credits = 0
    @categories.each do |category|
      @all_credits += category.credits if category.root?   #親区分だけ足す
    end
    @all_credits #単位の総数
  end

  def show
    @course = Course.find(id: params[:id])
  end

  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.build(course_params)
    if @course.save
      flash[:success] = "追加しました"
      redirect_to courses_path
    else
      render "new", status: :unprocessable_entity
    end
  end

  def edit
    @course = Course.find(id: params[:id])
  end

  def update
    @course = Course.find(id: params[:id])
    if @course.update(course_params)
      flash[:success] = "更新しました"
      redirect_to courses_path
    end
      render "edit", status: :unprocessable_entity
  end

  def destroy
    Course.find(id: params[:id])
    flash[:success] = "削除しました"
    redirect_to courses_path, status: :see_other
  end

  private
    def course_params
      params.require(:course).permit(:name, :credits, :category_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      forwarding_url = session[:forwarding_url]
      reset_session
      log_in user
      flash[:success] = "ログインしました"
      redirect_to forwarding_url || user
    else
      flash.now[:danger] = "メールアドレスまたはパスワードが正しくありません。"
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out
    flash[:success] = "ログアウトしました"
    redirect_to login_url, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show, :edit, :update, :withdraw, :destroy]
  before_action :correct_user,   only: [:show, :edit, :update, :withdraw, :destroy]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      flash[:success] = "登録が完了しました"
      redirect_to @user
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "更新しました"
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:notice] = "削除しました"
    redirect_to new_user_path, status: :see_other
  end

  def withdraw
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

    # beforeフィルタ

    # ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください"
        redirect_to login_url, status: :see_other
      end
    end

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(current_user, status: :see_other) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 現在ログイン中のユーザーを返す（いる場合）
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

      # 現在のユーザーをログアウトする
  def log_out
    reset_session
    @current_user = nil   # 安全のため
  end

  # 渡されたユーザーがカレントユーザーであればtrueを返す
  def current_user?(user)
    user && user == current_user
  end

  # アクセスしようとしたURLを保存する
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/edit.html.erb
<% provide(:title, "科目区分編集") %>
<h2 class="title">科目区分編集</h2>
<div class="form">
  <%= form_with(model: @category) do |f| %>
    <div class="form-item">
      <%= f.label :name,"区分名" %>
      <%= f.text_field :name %>
    </div>
    <div class="form-item">
      <%= f.label :credits,"単位数" %>
      <%= f.number_field :credits %>
    </div>
    <div class="form-item">
      <%= f.label :credits,"親区分（サブ区分の場合）" %>
      <div class="select-box">
        <%= f.select :ancestry, options_for_select(Category.where(user_id: current_user.id).where(ancestry: nil)
          .map{|o| [o.name, o.id]}, @category.ancestry), { include_blank: "------" } %>
      </div>
    </div>
    <div class="btn-wrapper">
      <%= f.submit "更新", class: "btn btn-blue" %>
    </div>
  <% end %>
</div>

app/views/categories/index.html.erb
<% provide(:title, "科目区分") %>
<h2 class="title">科目区分</h2>
<div class="btn-wrapper">
  <%= link_to new_category_path, class: "btn btn-blue" do %>
    <i class="fa-solid fa-plus"></i> 追加
  <% end %>
</div>
<ul class="category-list">
  <% @categories.each do |category| %>
    <% if category.root? %> <!-- 親カテゴリーを確認 -->
      <% if category.children.any? %>
        <li class="parent_category-list">
          <%= link_to category, class: "link_to_show category_name_in_parent_category_list" do %>
            <%= category.name %>
          <% end %>
          <ul>
            <% credits_sum = 0 %>
            <% category.children.each do |child| %>
              <li class="child_category-list">
                <%= link_to child, class: "link_to_show category_name_in_child_category_list" do %>
                  <%= child.name %>
                <% end %>
                <p><%= child.credits %></p>
              </li>
              <% credits_sum += child.credits %>
            <% end %>
          </ul>
          <% if category.credits >= credits_sum %>
            <p><%= category.credits %></p>
          <% else %>
            <p><%= credits_sum %></p>
          <% end %>
        </li>
      <% else %>
        <li class="parent_category-list_without_child">
          <%= link_to category, class: "link_to_show category_name_in_parent_category_list_without_child" do %>
            <%= category.name %>
          <% end %>
          <p><%= category.credits %></p>
        </li>
      <% end %>
    <% end %>
  <% end %>
  <li class="parent_category-list_without_child">
    <h3>合計</h3>
    <p><%= @all_credits %></p>
  </li>
</ul>

app/views/categories/new.html.erb
<% provide(:title, "科目区分追加") %>
<h2 class="title">科目区分追加</h2>
<div class="form">
  <%= form_with(model: @category) do |f| %>
    <div class="form-item">
      <%= f.label :name,"区分名" %>
      <%= f.text_field :name %>
    </div>
    <div class="form-item">
      <%= f.label :credits,"単位数" %>
      <%= f.number_field :credits %>
    </div>
    <div class="form-item">
      <%= f.label :credits,"親区分（サブ区分の場合）" %>
      <div class="select-box">
        <%= f.select :ancestry, options_for_select(Category.where(user_id: current_user.id).where(ancestry: nil)
          .map{|o| [o.name, o.id]}), { include_blank: "------" } %>
      </div>
    </div>
    <div class="btn-wrapper">
      <%= f.submit "追加", class: "btn btn-blue" %>
    </div>
  <% end %>
</div>

app/views/categories/show.html.erb
<% provide(:title, @category.name) %>
<h2 class="title"><%= @category.name %></h2>

<div class="btn-wrapper">
  <%= link_to new_category_path, class: "btn btn-blue" do %>
    <i class="fa-solid fa-plus"></i> 追加
  <% end %>
</div>
<ul class="category-list">
  <% if @category.root? %> <!-- 親カテゴリーを確認 -->
    <% if @category.children.any? %>
      <li class="parent_category-list">
        <h3 class="category_name_in_parent_category_list"><%= @category.name %></h3>
        <ul>
          <% @category.children.each do |child| %>
            <li class="child_category-list">
              <h4 class="category_name_in_child_category_list"><%= child.name %></h4>
              <p><%= child.credits %></p>
            </li>
          <% end %>
        </ul>
        <p><%= @category.credits %></p>
      </li>
    <% else %>
      <li class="parent_category-list_without_child">
        <h3 class="category_name_in_parent_category_list_without_child"><%= @category.name %></h3>
        <p><%= @category.credits %></p>
      </li>
    <% end %>
  <% else %>
    <li class="parent_category-list_without_child">
      <h3 class="category_name_in_parent_category_list_without_child"><%= @category.name %></h3>
      <p><%= @category.credits %></p>
    </li>
  <% end %>
</ul>


<div class="btn-wrapper">
  <%= link_to "編集", edit_category_path(@category), method: :get, class: "btn btn-blue" %>
</div>
<div class="btn-wrapper">
  <%= link_to "削除", @category, class: "btn btn-red",
    data: { "turbo-method": :delete, turbo_confirm: "本当に削除しますか？" } %>
</div>

app/views/courses/edit.html.erb
<h1>Courses#edit</h1>
<p>Find me in app/views/courses/edit.html.erb</p>

app/views/courses/index.html.erb
<% provide(:title, "授業一覧") %>
<h2 class="title">授業一覧</h2>

<ul class="parent-category-list">
  <% @grand_total_credits = 0 %>  <!-- 全授業の単位数の合計 -->
  <% @categories.each do |category| %>
    <% if category.root? %> <!-- 親カテゴリーか？ -->
      <% if category.children.any? %> <!-- 子カテゴリーをもつとき -->
        <% total_parent_credits = category.children.sum { |child| child.courses.sum(:credits) } %> <!-- 親カテゴリー内の授業の単位数の合計 -->
        <% @grand_total_credits += total_parent_credits %> <!-- 親カテゴリー内の授業の単位数の合計を、全授業の単位数の合計に加算 -->
        <li class="parent-category-item"> <!-- 親カテゴリー -->
          <div class="name-and-credits">
            <%= link_to category, class: "link_to_show" do %>
              <%= category.name %>
            <% end %>
            <p><%= total_parent_credits %> / <%= category.credits %></p>
          </div>
          <ul class="child-category-list">
            <% category.children.each do |child| %>
            <% total_child_credits = child.courses.sum(:credits) %> <!-- 子カテゴリー内の授業の単位数の合計 -->
              <li class="child-category-item"> <!-- 子カテゴリー -->
                <div class="name-and-credits">
                  <%= link_to child, class: "link_to_show" do %>
                    <%= child.name %>
                  <% end %>
                  <p><%= total_child_credits %> / <%= child.credits %></p>
                </div>
                <ul class="course-list">
                  <% courses = child.courses.all %>
                  <% courses.each do |course| %>
                    <li class="course-item"> <!-- 子カテゴリー内の授業 -->
                      <p><%= course.name %></p>
                      <p><%= course.credits %></p>
                    </li>
                  <% end %>
                </ul>
              </li>
            <% end %>
          </ul>
        </li>
      <% else %> <!-- 子カテゴリーをもたないとき -->
        <% total_parent_credits = category.courses.sum(:credits) %> <!-- 親カテゴリー内の授業の単位数の合計 -->
        <% @grand_total_credits += total_parent_credits %> <!-- 親カテゴリー内の授業の単位数の合計を、全授業の単位数の合計に加算 -->
        <li class="parent-category-item"> <!-- 親カテゴリー -->
          <div class="name-and-credits">
            <%= link_to category, class: "link_to_show" do %>
              <%= category.name %>
            <% end %>
            <p><%= total_parent_credits %> / <%= category.credits %></p>
          </div>
          <ul class="course-list">
            <% courses = category.courses.all %>
            <% courses.each do |course| %>
              <li class="course-item"> <!-- 親カテゴリー内の授業 -->
                <p><%= course.name %></p>
                <p><%= course.credits %></p>
              </li>
            <% end %>
          </ul>
        </li>
      <% end %>
    <% end %>
  <% end %>
  <li class="parent-category-item">
    <div class="name-and-credits">
      <p>合計</p>
      <p><%= @grand_total_credits %> / <%= @all_credits %></p>
    </div>
  </li>
</ul>

app/views/courses/new.html.erb
<h1>Courses#new</h1>
<p>Find me in app/views/courses/new.html.erb</p>

app/views/courses/show.html.erb
<h1>Courses#show</h1>
<p>Find me in app/views/courses/show.html.erb</p>

app/views/layouts/_footer.html.erb
<footer>
  <small>&copy; 2024 Koki Kitamura</small>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <div class="container header-container">
    <h1><%= link_to "Credit Manager", "#" %></h1>
    <nav>
      <ul class="nav">
      <% if logged_in? %>
        <li class="nav-item"><%= link_to "授業一覧", courses_path %></li>
        <li class="nav-item"><%= link_to "科目区分", categories_path %></li>
        <li class="nav-item" ><%= link_to "アカウント ▼", '#' %>
          <ul class="dropdown-lists">
            <li class="dropdown-list"><%= link_to "アカウント情報", current_user %></li>
            <li class="dropdown-list"><%= link_to "アカウント設定", edit_user_path(current_user) %></li>
            <li class="dropdown-list"><%= link_to "ログアウト", logout_path, data: { "turbo-method": :delete } %></li>
          </ul>
        </li>
      <% else %>
        <li class="nav-item"><%= link_to "ログイン", login_path %></li>
      <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title><%= yield(:title) %> | Credit Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/bceee67497.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li class="error-message"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "アカウント設定") %>
<h2 class="title">アカウント設定</h2>
<div class="form">
  <%= form_with(model: @user) do |f| %>
    <%= render 'shared/error_messages' %>
    <div class="form-item">
      <%= f.label :email,"メールアドレス" %>
      <%= f.email_field :email %>
    </div>
    <div class="form-item">
      <%= f.label :password, "新しいパスワード（6文字以上）" %>
      <%= f.password_field :password %>
    </div>
    <div class="form-item">
      <%= f.label :password_confirmation, "新しいパスワードの確認" %>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="btn-wrapper">
      <%= f.submit "変更", class: "btn btn-blue" %>
    </div>
  <% end %>
  <p><%= link_to "アカウント削除", "withdraw" %></p>
</div>

app/views/users/new.html.erb
<% provide(:title, "新規登録") %>
<h2 class="title">新規登録</h2>
<div class="form">
  <%= form_with(model: @user) do |f| %>
    <%= render 'shared/error_messages' %>
    <div class="form-item">
      <%= f.label :email,"メールアドレス" %>
      <%= f.email_field :email %>
    </div>
    <div class="form-item">
      <%= f.label :password, "パスワード（6文字以上）" %>
      <%= f.password_field :password %>
    </div>
    <div class="form-item">
      <%= f.label :password_confirmation, "パスワードの確認" %>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="btn-wrapper">
      <%= f.submit "登録", class: "btn btn-blue" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, "アカウント") %>
<h2 class="title">アカウント</h2>
<div class="account-show-item">
  <h3>メールアドレス</h3>
  <p><%= @user.email %></p>
</div>
<div class="account-show-item">
  <h3>パスワード</h3>
  <p>●●●●●●</p>
</div>
<div class="btn-wrapper">
<%= link_to "アカウント設定", edit_user_path(@user), method: :get, class: "btn btn-blue" %>
</div>

app/views/users/withdraw.html.erb
<% provide(:title, "アカウント削除") %>
<h2 class="title">アカウント削除</h2>

<div class="warning">
  <ol>
    <li>このアカウントに登録された全ての情報が削除されます。</li>
    <li class="bold">一度削除したアカウントは二度と復元できません。</li>
  </ol>
</div>

<div class="btn-wrapper">
  <%= link_to "削除しない", edit_user_path(@user), method: :get, class: "btn btn-red" %>
</div>
<div class="center">
  <p><%= link_to "削除", @user, data: { "turbo-method": :delete, turbo_confirm: "本当に削除しますか？" } %></p>
</div>